# Find all the available rules by running:
# swiftlint rules
#

# rule identifiers to exclude from running
disabled_rules:
    - force_try
    - todo
    - trailing_whitespace
    - type_name
    - large_tuple
    - redundant_optional_initialization
    - force_cast
    - superfluous_disable_command
    - identifier_name
    - weak_delegate
    #- operator_whitespace
    #- vertical_whitespace
    #- function_parameter_count
    #- cyclomatic_complexity
    #- type_body_length
    #- operator_whitespace
    #- colon
    #- comma
    #- control_statement

# paths to ignore during linting. Takes precedence over `included`.
excluded:
    - Carthage

# configurable rules can be customized from this configuration file
line_length:
    warning: 260
    error: 400
type_body_length:
    warning: 300
    error: 500
function_body_length:
    warning: 80
    error: 120
