# Find all the available rules by running:
# swiftlint rules
#

opt_in_rules:
    - unhandled_throwing_task
    - empty_count
    - first_where
    - weak_delegate
    - contains_over_filter_is_empty
    - contains_over_filter_count


disabled_rules:
    - todo
    - trailing_whitespace
    - type_name
    - superfluous_disable_command
    - force_cast
    - identifier_name
    - trailing_comma
    - cyclomatic_complexity
    - blanket_disable_command
    - for_where
    - nesting
    - redundant_optional_initialization
    - trailing_newline

# paths to ignore during linting. Takes precedence over `included`.
excluded:
    - Modules/Core/Sources/Assets/Colors.swift
    - Modules/Core/Sources/Assets/Images.swift
    - Modules/Core/Sources/Assets/Strings.swift

# configurable rules can be customized from this configuration file
line_length:
    warning: 260
    error: 400
type_body_length:
    warning: 1000
    error: 1000
function_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1200
    
force_try:
    severity: warning
large_tuple:
    warning: 5
    error: 7
