#!/bin/bash
STRINGS_PATH={{cookiecutter.projectName}}Kit/SupportingFiles/
STRINGS_HELPER_PATH={{cookiecutter.projectName}}Kit/Code/
SUPPORTING_FILES_PATH={{cookiecutter.projectName}}/SupportingFiles/
google-docs-i18n-strings -s {{cookiecutter.googleSheetId}} -p ios,iosUtil,iosPlist -i $STRINGS_PATH -u $STRINGS_HELPER_PATH -l $SUPPORTING_FILES_PATH

# Generate .stringsdict files for each .strings file
ruby strings_dict.rb -d "$STRINGS_PATH"