#!/bin/bash
STRINGS_PATH={{cookiecutter.projectName}}Kit/SupportingFiles/
STRINGS_HELPER_PATH={{cookiecutter.projectName}}Kit/Code/
google-docs-i18n-strings -s {{cookiecutter.googleSheetId}} -p ios,iosUtil -i $STRINGS_PATH -u STRINGS_HELPER_PATH
