// Generated by aaa string tool. Do _not_ modify.

import Foundation

// swiftlint:disable line_length
public struct Strings {
    public struct Network {
        static let errorGeneric = Strings.localized("network_error_generic", value: "Ein Fehler ist aufgetreten.")
        static let errorLoadingFailed = Strings.localized("network_error_loading_failed", value: "Daten konnten nicht geladen werden. (Code %1$@)")
        static let errorNoConnection = Strings.localized("network_error_no_connection", value: "Keine Netzwerkverbindung. Bitte versuchen Sie es später erneut.")
        static let errorPostingFailed = Strings.localized("network_error_posting_failed", value: "Daten konnten nicht übertragen werden. (Code %1$@)")
        static let errorWrongCredentials = Strings.localized("network_error_wrong_credentials", value: "Sie haben einen falschen Usernamen oder ein falsches Passwort eingegeben. Bitte versuchen Sie es erneut.")
    }

    // settings this closure allows you to use a custom localization provider, such as OneSky over-the-air
    // by default, NSLocalizedString will load the strings from the main bundle's Localizable.strings file
    public static var customLocalizationClosure: ((String, String?, Bundle, String, String) -> String)?

    public static func localized(_ key: String, tableName: String? = nil, bundle: Bundle = Bundle.main, value: String, comment: String = "") -> String {
        if let closure = Strings.customLocalizationClosure {
            return closure(key, tableName, bundle, value, comment)
        } else {
            return NSLocalizedString(key, tableName: tableName, bundle: bundle, value: value, comment: comment)
        }
    }
}
